name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image tag
        id: tag
        run: echo "image-tag=puck3/freshwave:latest" >> $GITHUB_OUTPUT

      - name: Create .env file for Docker
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker image
        run: docker build -t ${{ steps.tag.outputs.image-tag }} .

      - name: Save Docker image
        run: docker save -o /tmp/docker-image.tar ${{ steps.tag.outputs.image-tag }}

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: |
            /tmp/docker-image.tar

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download Docker image
        uses: actions/download-artifact@v5
        with:
          name: docker-image
          path: /tmp

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar

      - name: Push Docker image
        run: docker push ${{ needs.build.outputs.image-tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible playbook
        working-directory: ansible
        env:
          ANSIBLE_HOST: ${{ secrets.ANSIBLE_HOST }}
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PORT: ${{ secrets.ANSIBLE_PORT }}
        run: |
          envsubst < inventory/hosts.yml > inventory/hosts.generated.yml
          ansible-galaxy install -r requirements.yml
          ansible-playbook -i inventory/hosts.generated.yml playbook.yml \
            --vault-password-file <(echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}")
